clustalWeb/app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from .main import main as main_blueprint
from config import Config
bootstrap=Bootstrap()

def create_app():
    app=Flask(__name__)
    bootstrap.init_app(app)
    app.config.from_object(Config)
    app.register_blueprint(main_blueprint)
    return app

clustalWeb/app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import errors,views

clustalWeb/app/main/views.py
import os
import time
from flask import render_template, url_for, flash, redirect, request,send_from_directory
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, FileField
from wtforms.validators import DataRequired
from . import main
from .fastaOp import saveFasta
from .seqAli import clu

# 序列提交用表单类
class SeqForm(FlaskForm):
    seqName1 = StringField('序列名')
    seqData1 = TextAreaField('序列')
    seqName2 = StringField('序列名')
    seqData2 = TextAreaField('序列')
    seqSubmit = SubmitField('提交')
    seqFile = FileField('序列文件')


@main.route('/')
def space():
    return redirect(url_for('main.index'))

@main.route('/index', methods=['POST', 'GET'])
def index():
   # 表单类实例化
    SeqToForm = SeqForm()

    # 序列验证触发
    if SeqToForm.validate_on_submit():
    # if request.method == 'POST':
        workTime = time.strftime("%Y-%m-%d %H_%M_%S", time.localtime())
        # 若上传文件存在
        # try :
        seqFile = request.files['seqFile']
        if seqFile.filename == '':
          seqName1 = SeqToForm.seqName1.data
          seqData1 = SeqToForm.seqData1.data
          seqName2 = SeqToForm.seqName2.data
          seqData2 = SeqToForm.seqData2.data
          if seqData1=='' or seqData2=='':
            return redirect(url_for('main.inputError'))
          else:
            seq1={seqName1:seqData1}
            seq2={seqName2:seqData2}
            saveFasta(workTime,seq1,seq2)
        else :
          fileName = "Sequences" + workTime + ".fasta"
          basepath = os.path.dirname(__file__)  # 当前文件所在路径
          uploadPath = os.path.join(basepath, 'history', fileName)  #注意：没有的文件夹一定要先创建，不然会提示没有该路径
          seqFile.save(uploadPath)
          flash("Upload success! ")
        

        # finally:
        return redirect(url_for('main.cluResult', workTime=workTime))
    return render_template('clustal.html', form=SeqToForm)

@main.route('/cluResult/<workTime>')
def cluResult(workTime):
  # try:
  alnOpt=clu(workTime)
  # print(alnOpt)
  basepath = os.path.dirname(__file__)
  alnName = "Aligned" + workTime + ".aln"
  alnPath = os.path.join(basepath, "./output/" + alnName)
  # except :
    # flash("Your input outlaw!")
  return render_template('clustalResult.html', output=alnOpt, alnName=alnName, alnPath=alnPath)

@main.route('/cluResultdownload<alnName>')
def alnDownload(alnName):
  basepath = os.path.dirname(__file__)
  # alnName = "Aligned" + workTime + ".aln"
  alnPath = os.path.join(basepath, "./output/") 
  return send_from_directory(alnPath, alnName, as_attachment=True)

clustalWeb/app/templates/base.html
{% extends "bootstrap/base.html" %}
{% block title %}Flasky{% endblock %}
{% block navbar %}
<div class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" herf="/">Flasky</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="/">Home</a></li>
      </ul>
    </div>
  </div>
</div>
{% endblock %}
{% block content %}
<div class="container">
  {% block page_content %}{% endblock %}
</div>
{% endblock %}

clustalWeb/app/templates/baseModule.html
<html>

<head>
  { % block head %}
  <title>{% block title %}{% end block %} - My Application</title>
  {% endblock %}
</head>

<body>
  {% block body %}
  {% endblock %}
</body>

</html>

clustalWeb/app/templates/clustal.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>快速序列比对系统</title>
  <!-- CSS only -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="../static/css/blast.css">
  <!-- JS, Popper.js, and jQuery -->
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
    crossorigin="anonymous"></script>

</head>

<body>
  <div class="container-fluid fruitBg blur">

     <nav class="navbar navbar-expand-lg navbar-expand-md navbar-dark bg-light nav_bar">
      <div class="container-fluid">
        <a class="navbar-brand nav_bar nav1" href="teachNet.html">快速序列比对</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
          </ul>
         
        </div>
      </div>
    </nav> 

    <div class="row spaceUseLogin">
    <div  class=" col-sm-3 col-md-3 col-bg-3 offset-md-1 offset-md-1 containerBox shadow p-3 mb-5 bg-white rounded containerBox">

      <div class="row">
        <div class="col-sm-12 col-md-12 col-bg-12 titleBox">序列A</div>
      </div>
      </br>
      <form action="" enctype='multipart/form-data' method='POST'>
        {{ form.csrf_token() }}
        <div class="row ">
          <div class="col-sm-5 col-md-5 col-bg-5 loginInputBox1">
            <!-- <input type="text" class="form-control inputBox1" name="seqName1" placeholder="请输入序列名"> -->
            {{ form.seqName1(class="form-control inputBox1", placeholder="请输入序列名")}}
            <span></span>
            
          </div>
        </div>
        <div class="row ">
          <div class="col-sm-5 col-md-5 col-bg-5 loginInputBox3">
            <!-- <textarea type="text" rows="6" class="form-control inputBox2" name='seqData1' placeholder="请输入序列"></textarea> -->
            {{ form.seqData1(rows="6", class="form-control inputBox2", placeholder="请输入序列")}}
            <span></span>
          </div>
        </div>
    </div>

    <div  class=" col-sm-3 col-md-3 col-bg-3 offset-md-1 offset-md-1 containerBox shadow p-3 mb-5 bg-white rounded containerBox">

        <div class="row">
          <div class="col-sm-12 col-md-12 col-bg-12 titleBox">序列B</div>
        </div>
        </br>
          <div class="row ">
            <div class="col-sm-5 col-md-5 col-bg-5 loginInputBox1">
              {{ form.seqName2(class="form-control inputBox1", placeholder="请输入序列名")}}
              <!-- <input type="text" class="form-control inputBox1" name="seqName2" placeholder="请输入序列名"> -->
            </div>
          </div>
          <div class="row ">
            <div class="col-sm-5 col-md-5 col-bg-5 loginInputBox3">
              <!-- <textarea type="text" rows="6" class="form-control inputBox2" name='seqData1' placeholder="请输入序列"></textarea> -->
              {{ form.seqData2(rows="6", class="form-control inputBox2", placeholder="请输入序列")}}
              <span></span>
            </div>
          </div>
        <!-- </form> -->
      </div>

      <div class="col-sm-12 col-md-12 col-bg-12 ">
        <div class="uploadWord">需要多序列比对？请上传文件：</div>
      </div>
      <div class="col-sm-12 col-md-12 col-bg-12 btn fileBtn">
        
          <input type="file" name="seqFile">
      
      </div>

    <div class="col-sm-12 col-md-12 col-bg-12">
      <!-- <button type="submit"
      class="btn btn-warning submitButton">提交</button> -->
       <!-- button原本的位置 -->
       {{ form.seqSubmit(class="btn btn-warning submitButton") }}
       {# 显示消息闪现的内容 #}
        {% for message in get_flashed_messages() %}
          {{ message }}
        {% endfor %}
    </div>
    
  </form>
    </div>
  </div>



  <div class="jumbotron text-center" style="margin-bottom:0 ;background-color:#252525d5 ;color: #ffffff">
    </br>
    <p>请使用Chrome，火狐或Opera浏览器，或IE10及以上的浏览器。有任何问题请联系QQ1321591813</p>
  </div>

</body>

</html>

clustalWeb/app/templates/clustalError.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>比对结果</title>
  <!-- CSS only -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="../static/css/blast.css">
  <!-- JS, Popper.js, and jQuery -->
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
    crossorigin="anonymous"></script>

</head>

<body>
  <div class="container-fluid fruitBg blur">
    

     <nav class="navbar navbar-expand-lg navbar-expand-md navbar-dark bg-light nav_bar">
      <div class="container-fluid">
        <a class="navbar-brand nav_bar nav1" href={{url_for('main.index')}}>返回上一层</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
          </ul>
         
        </div>
      </div>
    </nav> 
    <div class="row spaceUseLogin">
    <div  class=" col-sm-6 col-md-6 col-bg-6 offset-md-2 offset-md-2 containerBox shadow p-3 mb-5 bg-white rounded containerBox">

      <div class="row ">
        <div class="col-sm-12 col-md-12 col-bg-12 titleBox">比对结果</div>
      </div>
      </br>
        <div class="row ">
          <div>
             {{ output }}</br>
          </div>
        </div>
    </div>
      <div class="row">
        <div class="downloadLink2">&nbsp&nbsp&nbsp&nbsp&nbsp点击下载aln文件：<a href={{url_for('main.alnDownload', alnName=alnName)}}>{{ alnName }}</a></div>
      </div>

    
    </div>

    
  </div>



  <div class="jumbotron text-center" style="margin-bottom:0 ;background-color:#252525d5 ;color: #ffffff">
    </br>
    <p>请使用Chrome，火狐或Opera浏览器，或IE10及以上的浏览器。有任何问题请联系QQ1321591813</p>
  </div>

</body>

</html>

clustalWeb/app/templates/clustalResult.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>比对结果</title>
  <!-- CSS only -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="../static/css/blast.css">
  <!-- JS, Popper.js, and jQuery -->
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
    crossorigin="anonymous"></script>

</head>

<body>
  <div class="container-fluid fruitBg blur">
    

     <nav class="navbar navbar-expand-lg navbar-expand-md navbar-dark bg-light nav_bar">
      <div class="container-fluid">
        <a class="navbar-brand nav_bar nav1" href={{url_for('main.index')}}>返回上一层</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
          </ul>
         
        </div>
      </div>
    </nav> 
    <div class="row spaceUseLogin">
    <div  class=" col-sm-6 col-md-6 col-bg-6 offset-md-2 offset-md-2 containerBox shadow p-3 mb-5 bg-white rounded containerBox">

      <div class="row ">
        <div class="col-sm-12 col-md-12 col-bg-12 titleBox">比对结果</div>
      </div>
      </br>
        <div class="row ">
          <div>
            {% for result in output %}
             {{ result.id }} {{ result.seq }}</br>
            {% endfor %}
          </div>
        </div>
    </div>
      <div class="row">
        <div class="downloadLink2">&nbsp&nbsp&nbsp&nbsp&nbsp点击下载aln文件：<a href={{url_for('main.alnDownload', alnName=alnName)}}>{{ alnName }}</a></div>
      </div>

    
    </div>

    
  </div>



  <div class="jumbotron text-center" style="margin-bottom:0 ;background-color:#252525d5 ;color: #ffffff">
    </br>
    <p>请使用Chrome，火狐或Opera浏览器，或IE10及以上的浏览器。有任何问题请联系QQ1321591813</p>
  </div>

</body>

</html>